name: build

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: vegidio/parse

jobs:
  push:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setting CalVer
        id: calver
        run: |
          echo "::set-output name=date::$(date +'%y.%-m').$GITHUB_RUN_NUMBER"

      - name: Build and run the Docker image
        run: |
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ steps.calver.outputs.date }}
          docker-compose up -d

      - name: Test the build
        run: |
          sleep 10
          yarn --cwd $GITHUB_WORKSPACE/test
          yarn --cwd $GITHUB_WORKSPACE/test test

      - name: Creating release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.calver.outputs.date }}
          release_name: Release ${{ steps.calver.outputs.date }}

      - name: Push new image into the registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ steps.calver.outputs.date }}